#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

//	while(true){
		servoTarget[servo1] = 237;
		servoTarget[servo3] = 149;
		wait10Msec(300);
	servoTarget[servo1] = 114;
	wait10Msec(100);
	servoTarget[servo3] = 71;
	wait10Msec(100);
	servoTarget[servo1] = 164;
	wait10Msec(100);
	//servoTarget[servo1] = 121;
	//wait10Msec(100);
	servoTarget[servo3] = 91;

	wait10Msec(100);

	servoTarget[servo3] = 103;
	wait10Msec(100);
	servoTarget[servo1] = 140;
	wait10Msec(100);
	servoTarget[servo3] = 79;
	wait10Msec(100);
	servoTarget[servo1] = 180;
	//}


}
