#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S2_C1_1,     driveLt,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     driveRt,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     rack,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "joystickDriver.c"
#include "autonomousMain.h"
#include "teleopMain.h"
#include "librobot.h"

task main(){
	while(true){
		getJoystickSettings(joystick);
		if (joystick.StopPgm){

			continue;
		}
		if (!joystick.UserMode){
			nxtDisplayTextLine(2, "Autonomous");
			autonMain();
		}
		else{nxtDisplayTextLine(2, "Teleop");
			teleMain();
		}
	}
}
