#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S2_C1_1,     driveLt,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     driveRt,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     rack,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickDriver.c"
#include "librobot.h"


void teleMain(){
	waitForStart(); //need this?
	int motorLeft = 0;
	int motorRight = 0;
    while(true){
				getJoystickSettings(joystick);

				motorLeft = (motorLeft + joystick.joy1_x1) / 2;
				motorRight = (motorRight + joystick.joy1_x1) / 2;
				motor[driveLt] = motorLeft;
				motor[driveRt] = motorRight;
				if(joy2Btn(5)==1){motor[flag] = 10;}
				if(joy2Btn(6)==1){motor[flag] = -10;}
				if(joy2Btn(7)==1){motor[flag] = 100;}
				if(joy2Btn(8)==1){motor[flag] = -100;}
			}
}
