#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Hubs,  S3, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     irseek,         sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S3_C1_1,     driveLt,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     driveRt,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C2_1,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_2,     wrist,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     should,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     should2,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C2_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     lift2,         tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    autonFlip,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    wrist1,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    wrist2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"



void initializeRobot()
{

 // noop
	return;
}


task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase

	int motorLeft = 0;
	int motorRight = 0;
	int flagv = 0;
	while(true){
		getJoystickSettings(joystick);
		wait1Msec(10);
		motorLeft = joystick.joy1_y1;
		motorRight = joystick.joy1_y2;
		motor[driveLt] = motorLeft;
		motor[driveRt] = motorRight;
		motor[should] = joystick.joy2_y1;
		motor[should2] =  joystick.joy2_y1;
		motor[wrist] = joystick.joy2_y2;
		if(joy1Btn(1)==1) {
			flagv--;
	}
		if(joy1Btn(3)==1) {
			flagv++;
	}
		if(joy2Btn(2)==1){
			nxtDisplayCenteredTextLine(2, "servoIn");
			// BEGIN NEW SERVO POSITIONING CODE, ONLY ONE POSITION!

			servoTarget[servo1] = 237;
			servoTarget[servo3] = 149;
			wait10Msec(40);
			servoTarget[servo1] = 114;
			wait10Msec(40);
			servoTarget[servo3] = 71;
			wait10Msec(40);
			servoTarget[servo1] = 164;
			wait10Msec(40);
			//servoTarget[servo1] = 121;
			//wait10Msec(100);
			servoTarget[servo3] = 91;

			wait10Msec(40);

			servoTarget[servo3] = 103;
			wait10Msec(40);
			servoTarget[servo1] = 140;
			wait10Msec(40);
			servoTarget[servo3] = 79;
			wait10Msec(40);
			servoTarget[servo1] = 180;
					// END NEW SERVO POSITIONING CODE, ONLY ONE POSITION!
		}
		if(joy2Btn(4)==1){
					// BEGIN NEW SERVO POSITIONING CODE, ONLY ONE POSITION!
			servoTarget[servo1] = 205;
			servoTarget[servo3] = 141;
			wait10Msec(40);

			servoTarget[servo1] = 196;
			servoTarget[servo3] = 61;
			wait10Msec(40);

			servoTarget[servo1] = 155;
			servoTarget[servo3] = 70;
			wait10Msec(40);

			servoTarget[servo1] = 170;
			servoTarget[servo3] = 69;
			wait10Msec(80);

			servoTarget[servo1] = 126;
			servoTarget[servo3] = 79;
			wait10Msec(40);
			servoTarget[servo1] = 237;
			servoTarget[servo3] = 149;
					// END NEW SERVO POSITIONING CODE, ONLY ONE POSITION!
		}
	}
}
