#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S2_C1_1,     driveFrLt,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     driveFrRt,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     driveBkLt,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     driveBkRt,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_1,     flagMtr,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_2,     armL,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickDriver.c"
#include "librobot.h"


void teleMain(){
	TOmniOutput motorEnergization;
	while(true){
		getJoystickSettings(joystick);
		TOmniOutput tempPreSmooth;
		calcoutput(joy1_y2, joy1_x2, joy1_x1, tempPreSmooth);
		smoothUpdate(tempPreSmooth, motorEnergization);
		motor[driveNE]=motorEnergization.motorNE;
		motor[driveSE]=motorEnergization.motorSE;
		motor[driveNW]=motorEnergization.motorNW;
		motor[driveSW]=motorEnergization.motorSW;
		if(joy1Btn(6)==1){motor[flagMtr]=100;}
		else if(joy1Btn(5)==1){motor[flagMtr]=-100;}
		else{motor[flagMtr]=0;}
		wait1Msec(1);

	}
}
